version: '3.5'

services:
 authenticationservice:
    image: authenticationservice
    ports:
     - "5000:80"    
    depends_on:
     - sqldb
    environment:     
     ConnectionString: "server=sqldb,1433;database=UserDb;User Id=sa;Password=Testsql@123;"

 newsservice:
    image: newsservice
    ports:
     - "5001:80"    
    depends_on:
     - mongodb
    environment:
     MongoDB: "mongodb://mongodb:27017"

 userservice:
    image: userservice
    ports:
     - "5002:80"    
    depends_on:
     - mongodb
    environment:
     MongoDB: "mongodb://mongodb:27017"

 reminderservice:
    image: reminderservice
    ports:
     - "5003:80"    
    depends_on:
     - mongodb
    environment:
     MongoDB: "mongodb://mongodb:27017"

 sqldb:
    image: mcr.microsoft.com/mssql/server:2017-latest   
    ports:
     - "1433:1433"
    environment:
     SA_PASSWORD: "Testsql@123"
     ACCEPT_EULA: "Y"     

 mongodb:
    image: mongo
    ports:
     - "27017:27017"
     